# packages in environment at /opt/anaconda3/envs/wired-utility:
#
# Name                    Version                   Build  Channel
affine                    2.3.0              pyhd3eb1b0_0  
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h80987f9_0  
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0          py312hca03da5_0  
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
blas                      1.0                    openblas  
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               h313beb8_0  
boost-cpp                 1.82.0               h48ca7d4_2  
bottleneck                1.3.7           py312ha86b861_0  
branca                    0.6.0           py312hca03da5_0  
brotli                    1.0.9                h80987f9_8  
brotli-bin                1.0.9                h80987f9_8  
brotli-python             1.0.9           py312h313beb8_8  
bzip2                     1.0.8                h80987f9_6  
c-ares                    1.19.1               h80987f9_0  
ca-certificates           2024.7.4             hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0               h302bd0f_5  
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h80987f9_1  
cfitsio                   3.470                h7f6438f_7  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py312hca03da5_0  
click-plugins             1.1.1              pyhd3eb1b0_0  
cligj                     0.7.2              pyhd3eb1b0_0  
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py312h48ca7d4_0  
cycler                    0.11.0             pyhd3eb1b0_0  
debugpy                   1.6.7           py312h313beb8_0  
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h313beb8_0  
fiona                     1.9.5           py312hd77ebd4_0  
folium                    0.17.0             pyhd8ed1ab_0    conda-forge
fontconfig                2.14.1               hee714a5_2  
fonttools                 4.51.0          py312h80987f9_0  
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h1192e45_0  
freexl                    2.0.0                ha3de405_0  
gdal                      3.6.2           py312h5ed0132_4  
geojson                   3.1.0              pyhd8ed1ab_0    conda-forge
geopandas                 0.14.2          py312hca03da5_0  
geopandas-base            0.14.2          py312hca03da5_0  
geos                      3.9.1                hc377ac9_1  
geotiff                   1.7.0                h41f0982_3  
gettext                   0.21.0               h13f89a0_1  
giflib                    5.2.1                h80987f9_3  
glib                      2.78.4               h313beb8_0  
glib-tools                2.78.4               h313beb8_0  
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.13               h5e329fb_3  
hdf5                      1.12.1               h05c076b_3  
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.1                 h313beb8_0  
idna                      3.7             py312hca03da5_0  
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4           py312hca03da5_0  
joblib                    1.4.2           py312hca03da5_0  
jpeg                      9e                   h80987f9_1  
json-c                    0.16                 h1a28f6b_0  
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312hca03da5_0  
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
kealib                    1.5.0                hba2eb73_1  
kiwisolver                1.4.4           py312h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libboost                  1.82.0               h0bc93f9_2  
libbrotlicommon           1.0.9                h80987f9_8  
libbrotlidec              1.0.9                h80987f9_8  
libbrotlienc              1.0.9                h80987f9_8  
libcurl                   8.7.1                h3e2b118_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_1  
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.4                hca03da5_1  
libgdal                   3.6.2                h0413ea8_4  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libglib                   2.78.4               h0a96307_0  
libiconv                  1.16                 h80987f9_3  
libkml                    1.3.0                hc4d7c42_7  
libnetcdf                 4.8.1                h0fce390_4  
libnghttp2                1.57.0               h62f6fdd_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.17                h02f6b3c_0  
libsodium                 1.0.18               h27ca646_1    conda-forge
libspatialindex           1.9.3                hc377ac9_0  
libspatialite             5.1.0                h87e580a_0  
libssh2                   1.11.0               h3e2b118_0  
libtiff                   4.5.1                h313beb8_0  
libwebp-base              1.3.2                h80987f9_0  
libxml2                   2.10.4               h0b34f26_2  
libzip                    1.8.0                h62fee54_1  
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_1  
mapclassify               2.5.0           py312hca03da5_0  
markupsafe                2.1.3           py312h80987f9_0  
matplotlib-base           3.8.4           py312hd77ebd4_0  
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
minizip                   4.0.3                ha89c15f_0  
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3             py312hca03da5_0  
notebook                  7.2.1              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h313beb8_0  
nss                       3.89.1               h313beb8_0  
numexpr                   2.8.7           py312h0f3ea24_0  
numpy                     1.26.4          py312h7f4fdc5_0  
numpy-base                1.26.4          py312he047099_0  
openjpeg                  2.4.0                h0ed58ac_2  
openssl                   3.3.1                hfb2fe0b_2    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1            py312hca03da5_0  
pandas                    2.2.2           py312hd77ebd4_0  
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                hb066dcc_1  
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py312h80987f9_0  
pip                       24.0            py312hca03da5_0  
pixman                    0.40.0               h1a28f6b_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
poppler                   22.12.0              h52f4003_3  
poppler-data              0.4.11               hca03da5_1  
proj                      9.3.1                h805f6d4_0  
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    5.9.0           py312h80987f9_0  
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pybind11-abi              5                    hd3eb1b0_0  
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.1            py312h80987f9_0  
pyobjc-framework-cocoa    10.1            py312hb094c41_0  
pyparsing                 3.0.9           py312hca03da5_0  
pyproj                    3.6.1           py312h4b40952_0  
pysocks                   1.7.1           py312hca03da5_0  
python                    3.12.3               h99e199e_1  
python-dateutil           2.9.0post0      py312hca03da5_2  
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2024.1          py312hca03da5_0  
pyyaml                    6.0.1           py312h80987f9_0  
pyzmq                     24.0.1          py312h80987f9_0  
qhull                     2020.2               h48ca7d4_2  
rasterio                  1.3.10          py312hee3c5bf_0  
readline                  8.2                  h1a28f6b_0  
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.2          py312hca03da5_0  
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.10.6          py312hf0e4da2_0  
rtree                     1.0.1           py312hca03da5_0  
scikit-learn              1.4.2           py312hd77ebd4_1  
scipy                     1.13.1          py312ha409365_0  
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                69.5.1          py312hca03da5_0  
shapely                   2.0.1           py312ha8c8ce4_1  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7              pyhd3eb1b0_0  
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlite                    3.45.3               h80987f9_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
threadpoolctl             3.5.0           py312h989b03a_0  
tiledb                    2.3.3                hb4a6b97_3  
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.14               h6ba3021_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h80987f9_0  
tqdm                      4.66.4          py312h989b03a_0  
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h04d1e81_0  
unicodedata2              15.1.0          py312h80987f9_0  
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.7                h80987f9_0  
urllib3                   2.2.2           py312hca03da5_0  
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.6.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0          py312hca03da5_0  
xerces-c                  3.2.4                h313beb8_1  
xyzservices               2022.9.0        py312hca03da5_1  
xz                        5.4.6                h80987f9_1  
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.5                h313beb8_0  
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h18a0788_1  
zstd                      1.5.5                hd90d995_2  
